# This is a basic workflow to help you get started with Actions

name: Test Project

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Runs a single command using the runners shell
      - name: Get code
        uses: actions/checkout@v4 
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
      - name: Install dependencies
        run : npm ci
      - name: Run tests
        run: npm test

